name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: npm install, npm run lint
      run: |
        npm install
        npm run lint
        npm run test
      env:
        CI: true
